# Generated by Django 3.2.5 on 2021-07-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('reg_date', models.DateTimeField(verbose_name='Date published')),
                ('content', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
